# Responsible for making comments on pull requests, such as commenting for first time contributors.
name: Pull Request Comments

on:
  pull_request_target:
    types: [ 'opened' ]


# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.event_name == 'workflow_dispatch' && github.event.number || github.sha }}

# Disable permissions for all available scopes by default.
# Any needed permissions should be configured at the job level.
permissions: {}

jobs:
  # Leaves a comment on a pull request when no Trac ticket is included in the pull request description.
  trac-ticket-check:
    name: Comment on a pull request when no Trac ticket is included
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Check for Trac ticket and comment if missing
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const { owner, repo } = context.repo;
            const { number } = context.issue;

            // Check for the presence of a comment and bail early.
            const comments = ( await github.rest.issues.listComments( { owner, repo, issue_number: number } ) ).data;

            const hasMissingTicketComment = comments.some( comment =>
              comment.user.type === 'Bot' && comment.body.includes( 'Trac Ticket Missing' )
            );

            if ( hasMissingTicketComment ) return;

            // No comment was found. Create one.
            const pr = ( await github.rest.pulls.get( { owner, repo, pull_number: number } ) ).data;

            const prBody = pr.body ?? '';
            const prTitle = pr.title ?? '';

            const tracTicketRegex = new RegExp( '(https?:\/\/core.trac.wordpress.org\/ticket\/|Core-)([0-9]+)', 'g' );
            const tracTicketMatches = prBody.match( tracTicketRegex ) || prTitle.match( tracTicketRegex );

            if ( ! tracTicketMatches ) {
              github.rest.issues.createComment( {
                owner,
                repo,
                issue_number: number,
                body: `## Trac Ticket Missing
            This pull request is missing a link to a [Trac ticket](https://core.trac.wordpress.org/). For a contribution to be considered, there must be a corresponding ticket in Trac.

            To attach a pull request to a Trac ticket, please include the ticket's full URL in your pull request description. More information about contributing to WordPress on GitHub can be found in [the Core Handbook](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/).
            `,
              } );
            }
